[metadata]
name = link_shortener
version = 0.1.0
description = Minimal URL shortener

[options]
packages = find:
python_requires = >=3.12
install_requires =
    fastapi
    uvicorn[standard]
    aiosqlite
    alembic
    sqlalchemy[asyncio]>=2.0
    pydantic
    redis
    pyyaml

[options.packages.find]
exclude =
    static*
    config*
    alembic*